In [1]:
import pandas as pd

data = {
    'name':['Ali','sara','Ahmed'],
    'age':[22,25,21],
    'salary':[50000,60000,45000]
}
df = pd.DataFrame(data)
print(df)

    name  age  salary
0    Ali   22   50000
1   sara   25   60000
2  Ahmed   21   45000

In [2]:
df.head()

    name  age  salary
0    Ali   22   50000
1   sara   25   60000
2  Ahmed   21   45000

In [4]:
df['salary']

0    50000
1    60000
2    45000
Name: salary, dtype: int64

In [5]:
df[df['salary'] > 50000]

   name  age  salary
1  sara   25   60000

In [9]:
df['tax'] = df['salary'] * 0.1

In [8]:
df['salary'].mean()

np.float64(51666.666666666664)